/*
 * This file is part of EmsBench.
 *
 * Copyright 2015 University of Augsburg
 *
 * EmsBench is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * EmsBench is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with EmsBench.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * $Id: header-ems.c 480 2015-10-27 12:42:40Z klugeflo $
 * @file DummyDefs.h
 * @ingroup allHeaders
 * @brief 
 * @author Andreas Meixner, Claudius Heine,
 * Florian Kluge <kluge@informatik.uni-augsburg.de>
 */

#ifndef FILE_DUMMYDEFS_H_SEEN
#define FILE_DUMMYDEFS_H_SEEN

#include <stdint.h>

extern volatile unsigned char ARMCOP; // DVUCP(0x003F)
extern volatile unsigned char ATD0CTL0; // DVUCP(0x02C0)
extern volatile unsigned char ATD0CTL1; // DVUCP(0x02C1)
extern volatile unsigned char ATD0CTL2; // DVUCP(0x02C2)
extern volatile unsigned char ATD0CTL3; // DVUCP(0x02C3)
extern volatile unsigned char ATD0CTL4; // DVUCP(0x02C4)
extern volatile unsigned char ATD0CTL5; // DVUCP(0x02C5)
extern volatile unsigned char ATD0DIEN; // DVUCP(0x02CD)
extern volatile unsigned short ATD0DR0; // DVUSP(ATD0_BASE + 0x0)
extern volatile unsigned short ATD0DR1; // DVUSP(ATD0_BASE + 0x2)
extern volatile unsigned short ATD0DR2; // DVUSP(ATD0_BASE + 0x4)
extern volatile unsigned short ATD0DR3; // DVUSP(ATD0_BASE + 0x6)
extern volatile unsigned short ATD0DR4; // DVUSP(ATD0_BASE + 0x8)
extern volatile unsigned short ATD0DR5; // DVUSP(ATD0_BASE + 0xA)
extern volatile unsigned short ATD0DR6; // DVUSP(ATD0_BASE + 0xC)
extern volatile unsigned short ATD0DR7; // DVUSP(ATD0_BASE + 0xE)
extern volatile unsigned char ATD0PER1; // DVUCP(0x0277)
extern volatile unsigned char ATD1CTL0; // DVUCP(0x0080)
extern volatile unsigned char ATD1CTL1; // DVUCP(0x0081)
extern volatile unsigned char ATD1CTL2; // DVUCP(0x0082)
extern volatile unsigned char ATD1CTL3; // DVUCP(0x0083)
extern volatile unsigned char ATD1CTL4; // DVUCP(0x0084)
extern volatile unsigned char ATD1CTL5; // DVUCP(0x0085)
extern volatile unsigned char ATD1DIEN0; // DVUCP(0x008C)
extern volatile unsigned char ATD1DIEN1; // DVUCP(0x008D)
extern volatile unsigned short ATD1DR0; // DVUSP(ATD1_BASE + 0x0)
extern volatile unsigned short ATD1DR1; // DVUSP(ATD1_BASE + 0x2)
extern volatile unsigned short ATD1DR2; // DVUSP(ATD1_BASE + 0x4)
extern volatile unsigned short ATD1DR3; // DVUSP(ATD1_BASE + 0x6)
extern volatile unsigned short ATD1DR4; // DVUSP(ATD1_BASE + 0x8)
extern volatile unsigned short ATD1DR5; // DVUSP(ATD1_BASE + 0xA)
extern volatile unsigned short ATD1DR6; // DVUSP(ATD1_BASE + 0xC)
extern volatile unsigned short ATD1DR7; // DVUSP(ATD1_BASE + 0xE)
extern volatile unsigned char CAN0CTL1; // DVUCP(0x0141)
extern volatile unsigned char CAN1CTL1; // DVUCP(0x0181)
extern volatile unsigned char CAN3CTL1; // DVUCP(0x0201)
extern volatile unsigned char CAN4CTL1; // DVUCP(0x0281)
extern volatile unsigned char CFORC; // DVUCP(0x0041)
extern volatile unsigned char CLKSEL; // DVUCP(0x0039)
extern volatile unsigned char COPCTL; // DVUCP(0x003C)
extern volatile unsigned char CRGFLG; // DVUCP(0x0037)
extern volatile unsigned char CRGINT; // DVUCP(0x0038)
extern volatile unsigned char DDRA; // DVUCP(0x0002)
extern volatile unsigned char DDRB; // DVUCP(0x0003)
extern volatile unsigned char DDRC; //  DVUCP(0x0006)
extern volatile unsigned char DDRD; //  DVUCP(0x0007)
extern volatile unsigned char DDRE; // DVUCP(0x0009)
extern volatile unsigned char DDRH; // DVUCP(0x0262)
extern volatile unsigned char DDRJ; // DVUCP(0x026A)
extern volatile unsigned char DDRK; // DVUCP(0x0033)
extern volatile unsigned char DDRM; // DVUCP(0x0252)
extern volatile unsigned char DDRP; // DVUCP(0x025A)
extern volatile unsigned char DDRS; // DVUCP(0x024A)
extern volatile unsigned char DDRT; // DVUCP(0x0242)
extern volatile unsigned char DLYCT; // DVUCP(0x0069)
extern volatile unsigned char ECLKCTL; // DVUCP(0x001C)
extern volatile unsigned short FADDR; // DVUSP(0x0108)
extern volatile unsigned char FCLKDIV; // DVUCP(0x0100)
extern volatile unsigned char FCMD; // DVUCP(0x0106)
extern volatile unsigned char FCNFG; // DVUCP(0x0103)
extern volatile unsigned char FCTL; // DVUCP(0x0107)
extern volatile unsigned short FDATA; // DVUSP(0x010A)
extern volatile unsigned char FPROT; // DVUCP(0x0104)
extern volatile unsigned char FSEC; // DVUCP(0x0101)
extern volatile unsigned char FSTAT;// DVUCP(0x0105)
extern volatile unsigned char ICOVW; // DVUCP(0x006A)
extern volatile unsigned char ICPAR; // DVUCP(0x0068)
extern volatile unsigned char ICSYS; // DVUCP(0x006B)
extern volatile unsigned char INT_CFADDR; // DVUCP(0x0127)
extern volatile unsigned char INT_CFDATA0; // DVUCP(0x0128)
extern volatile unsigned char INT_CFDATA1; // DVUCP(0x0129)
extern volatile unsigned char INT_CFDATA2; // DVUCP(0x012A)
extern volatile unsigned char INT_CFDATA3; // DVUCP(0x012B)
extern volatile unsigned char INT_CFDATA4; // DVUCP(0x012C)
extern volatile unsigned char INT_CFDATA5; // DVUCP(0x012D)
extern volatile unsigned char INT_CFDATA6; // DVUCP(0x012E)
extern volatile unsigned char INT_CFDATA7; // DVUCP(0x012F)
extern volatile unsigned char INT_XGPRIO; // DVUCP(0x0126)
extern volatile unsigned char IRQCR; // DVUCP(0x001E)
extern volatile unsigned char IVBR; // DVUCP(0x0121)
extern volatile unsigned short MCCNT; // DVUSP(0x0076)
extern volatile unsigned char MCCTL; // DVUCP(0x0066)
extern volatile unsigned char MCFLG; // DVUCP(0x0067)
extern volatile unsigned char MODRR; // DVUCP(0x0257)
extern volatile unsigned char OC7D; // DVUCP(0x0043)
extern volatile unsigned char OC7M; // DVUCP(0x0042)
extern volatile unsigned char PA0H; // DVUCP(0x0075)
extern volatile unsigned char PA1H; // DVUCP(0x0074)
extern volatile unsigned char PA2H; // DVUCP(0x0073)
extern volatile unsigned char PA3H; // DVUCP(0x0072)
extern volatile unsigned short PACHUS0; // DVUSP(0x0074)
extern volatile unsigned short PACHUS2; // DVUSP(0x0072)
extern volatile unsigned char PACN0; // DVUCP(0x0065)
extern volatile unsigned char PACN1; // DVUCP(0x0064)
extern volatile unsigned char PACN2; // DVUCP(0x0063)
extern volatile unsigned char PACN3; // DVUCP(0x0062)
extern volatile unsigned short PACNUS0; // DVUSP(0x0064)
extern volatile unsigned short PACNUS2; // DVUSP(0x0062)
extern volatile unsigned char PACTL; // DVUCP(0x0060)
extern volatile unsigned char PAFLG; // DVUCP(0x0061)
extern volatile unsigned char PBCTL; // DVUCP(0x0070)
extern volatile unsigned char PBFLG; // DVUCP(0x0071)
extern volatile unsigned char PERH; // DVUCP(0x0264)
extern volatile unsigned char PERJ; // DVUCP(0x026C)
extern volatile unsigned char PERM; // DVUCP(0x0254)
extern volatile unsigned char PERP; // DVUCP(0x025C)
extern volatile unsigned char PERS; // DVUCP(0x024C)
extern volatile unsigned char PERT; // DVUCP(0x0244)
extern volatile unsigned char PIEH; // DVUCP(0x0266)
extern volatile unsigned char PIEJ; // DVUCP(0x026E)
extern volatile unsigned char PIEP; // DVUCP(0x025E)
extern volatile unsigned char PIFH; // DVUCP(0x0267)
extern volatile unsigned char PIFJ; // DVUCP(0x026F)
extern volatile unsigned char PIFP; // DVUCP(0x025F)
extern volatile unsigned char PITCE; // DVUCP(0x0342)
extern volatile unsigned char PITCFLMT; // DVUCP(0x0340)
extern volatile unsigned short PITCNT0; // DVUSP(0x034A)
extern volatile unsigned short PITCNT1; // DVUSP(0x034E)
extern volatile unsigned short PITCNT2; // DVUSP(0x0352)
extern volatile unsigned short PITCNT3; // DVUSP(0x0356)
extern volatile unsigned char PITFLT; // DVUCP(0x0341)
extern volatile unsigned char PITINTE; // DVUCP(0x0344)
extern volatile unsigned short PITLD0; // DVUSP(0x0348)
extern volatile unsigned short PITLD1; // DVUSP(0x034C)
extern volatile unsigned short PITLD2; // DVUSP(0x0350)
extern volatile unsigned short PITLD3; // DVUSP(0x0354)
extern volatile unsigned char PITMTLD0; // DVUCP(0x0346)
extern volatile unsigned char PITMTLD1; // DVUCP(0x0347)
extern volatile unsigned char PITMUX; // DVUCP(0x0343)
extern volatile unsigned char PITTF; // DVUCP(0x0345)
extern volatile unsigned char PLLCTL; // DVUCP(0x003A)
extern volatile unsigned char PORTE; // DVUCP(0x0008)
extern volatile unsigned char PORTH; // DVUCP(0x0260)
extern volatile unsigned char PORTJ; // DVUCP(0x0268)
extern volatile unsigned char PORTK; // DVUCP(0x0032)
extern volatile unsigned char PORTM; // DVUCP(0x0250)
extern volatile unsigned char PORTP; // DVUCP(0x0258)
extern volatile unsigned char PORTS; // DVUCP(0x0248)
extern volatile unsigned char PORTT; // DVUCP(0x0240)
extern volatile unsigned char PPAGE; // DVUCP(0x0030)
extern volatile unsigned char PPSH; // DVUCP(0x0265)
extern volatile unsigned char PPSJ; // DVUCP(0x026D)
extern volatile unsigned char PPSM; // DVUCP(0x0255)
extern volatile unsigned char PPSP; // DVUCP(0x025D)
extern volatile unsigned char PPSS; // DVUCP(0x024D)
extern volatile unsigned char PPST; // DVUCP(0x0245)
extern volatile unsigned char PTH; // DVUCP(0x0260)
extern volatile unsigned char PTIH; // DVUCP(0x0261)
extern volatile unsigned char PTIJ; // DVUCP(0x0269)
extern volatile unsigned char PTIM; // DVUCP(0x0251)
extern volatile unsigned char PTIP; // DVUCP(0x0259)
extern volatile unsigned char PTIS; // DVUCP(0x0249)
extern volatile unsigned char PTIT; // DVUCP(0x0241)
extern volatile unsigned char PTJ; // DVUCP(0x0268)
extern volatile unsigned char PTM; // DVUCP(0x0250)
extern volatile unsigned char PTMCPSR; // DVUCP(0x006F)
extern volatile unsigned char PTP; // DVUCP(0x0258)
extern volatile unsigned char PTPSR; // DVUCP(0x006E)
extern volatile unsigned char PTS; // DVUCP(0x0248)
extern volatile unsigned char PTT; // DVUCP(0x0240)
extern volatile unsigned char PUCR; // DVUCP(0x000C)
extern volatile unsigned char PWMCAE; // DVUCP(0x0304)
extern volatile unsigned char PWMCLK; // DVUCP(0x0302)
extern volatile unsigned char PWMCNT0; // DVUCP(0x030C)
extern volatile unsigned char PWMCNT1; // DVUCP(0x030D)
extern volatile unsigned char PWMCNT2; // DVUCP(0x030E)
extern volatile unsigned char PWMCNT3; // DVUCP(0x030F)
extern volatile unsigned char PWMCNT4; // DVUCP(0x0310)
extern volatile unsigned char PWMCNT5; // DVUCP(0x0311)
extern volatile unsigned char PWMCNT6; // DVUCP(0x0312)
extern volatile unsigned char PWMCNT7; // DVUCP(0x0313)
extern volatile unsigned char PWMCTL; // DVUCP(0x0305)
extern volatile unsigned char PWMDTY0; // DVUCP(0x031C)
extern volatile unsigned char PWMDTY1; // DVUCP(0x031D)
extern volatile unsigned char PWMDTY2; // DVUCP(0x031E)
extern volatile unsigned char PWMDTY3; // DVUCP(0x031F)
extern volatile unsigned char PWMDTY4; // DVUCP(0x0320)
extern volatile unsigned char PWMDTY5; // DVUCP(0x0321)
extern volatile unsigned char PWMDTY6; // DVUCP(0x0322)
extern volatile unsigned char PWMDTY7; // DVUCP(0x0323)
extern volatile unsigned char PWME; // DVUCP(0x0300)
extern volatile unsigned char PWMPER0; // DVUCP(0x0314)
extern volatile unsigned char PWMPER1; // DVUCP(0x0315)
extern volatile unsigned char PWMPER2; // DVUCP(0x0316)
extern volatile unsigned char PWMPER3; // DVUCP(0x0317)
extern volatile unsigned char PWMPER4; // DVUCP(0x0318)
extern volatile unsigned char PWMPER5; // DVUCP(0x0319)
extern volatile unsigned char PWMPER6; // DVUCP(0x031A)
extern volatile unsigned char PWMPER7; // DVUCP(0x031B)
extern volatile unsigned char PWMPOL; // DVUCP(0x0301)
extern volatile unsigned char PWMPRCLK; // DVUCP(0x0303)
extern volatile unsigned char PWMSCLA; // DVUCP(0x0308)
extern volatile unsigned char PWMSCLB; // DVUCP(0x0309)
extern volatile unsigned char PWMSDN; // DVUCP(0x0324)
extern volatile unsigned char RDRH; // DVUCP(0x0263)
extern volatile unsigned char RDRIV; // DVUCP(0x000D)
extern volatile unsigned char RDRJ; // DVUCP(0x026B)
extern volatile unsigned char RDRM; // DVUCP(0x0253)
extern volatile unsigned char RDRP; // DVUCP(0x025B)
extern volatile unsigned char RDRS; // DVUCP(0x024B)
extern volatile unsigned char RDRT; // DVUCP(0x0243)
extern volatile unsigned char REFDV; // DVUCP(0x0035)
extern volatile unsigned char RPAGE; // DVUCP(0x0016)
extern volatile unsigned char RTICTL; // DVUCP(0x003B)
extern volatile unsigned char SCI0ACR1; // DVUCP(SCI0_BASE + 0x1)
extern volatile unsigned char SCI0ACR2; // DVUCP(SCI0_BASE + 0x2)
extern volatile unsigned char SCI0ASR1; // DVUCP(SCI0_BASE + 0x0)
extern volatile unsigned short SCI0BD; // DVUSP(SCI0_BASE + 0x0)
extern volatile unsigned char SCI0CR1; // DVUCP(SCI0_BASE + 0x2)
extern volatile unsigned char SCI0CR2; // DVUCP(SCI0_BASE + 0x3)
extern volatile unsigned char SCI0DRH; // DVUCP(SCI0_BASE + 0x6)
extern volatile unsigned char SCI0DRL; // DVUCP(SCI0_BASE + 0x7)
extern volatile unsigned char SCI0SR1; // DVUCP(SCI0_BASE + 0x4)
extern volatile unsigned char SCI0SR2; // DVUCP(SCI0_BASE + 0x5)
extern volatile unsigned char SYNR; // DVUCP(0x0034)
extern volatile unsigned short TC0; // DVUSP(0x0050)
extern volatile unsigned short TC0H; // DVUSP(0x0078)
extern volatile unsigned short TC1; // DVUSP(0x0052)
extern volatile unsigned short TC1H; // DVUSP(0x007A)
extern volatile unsigned short TC2; // DVUSP(0x0054)
extern volatile unsigned short TC2H; // DVUSP(0x007C)
extern volatile unsigned short TC3; // DVUSP(0x0056)
extern volatile unsigned short TC3H; // DVUSP(0x007E)
extern volatile unsigned short TC4; // DVUSP(0x0058)
extern volatile unsigned short TC5; // DVUSP(0x005A)
extern volatile unsigned short TC6; // DVUSP(0x005C)
extern volatile unsigned short TC7; // DVUSP(0x005E)
//extern volatile unsigned short TCNT; // DVUSP(0x0044)
extern volatile unsigned char TCTL1; // DVUCP(0x0048)
extern volatile unsigned char TCTL2; // DVUCP(0x0049)
extern volatile unsigned char TCTL3; // DVUCP(0x004A)
extern volatile unsigned char TCTL4; // DVUCP(0x004B)
extern volatile unsigned char TFLG; // DVUCP(0x004E)
extern volatile unsigned char TFLGOF; // DVUCP(0x004F)
extern volatile unsigned char TIE; // DVUCP(0x004C)
extern volatile unsigned char TIOS; // DVUCP(0x0040)
extern volatile unsigned char TSCR1; // DVUCP(0x0046)
extern volatile unsigned char TSCR2; // DVUCP(0x004D)
extern volatile unsigned char TTOV; // DVUCP(0x0047)
extern volatile unsigned char VREGAPICL; // DVUCP(0x02F2)
extern volatile unsigned short VREGAPIR; // DVUSP(0x02F4)
extern volatile unsigned char VREGAPITR; // DVUCP(0x02F3)
extern volatile unsigned char VREGCTRL; // DVUCP(0x02F1)
extern volatile unsigned char WOMM; // DVUCP(0x0256)
extern volatile unsigned char WOMS; // DVUCP(0x024E)
extern volatile unsigned char XGCCR; // DVUCP(0x039D)
extern volatile unsigned char XGCHID; // DVUCP(0x0382)
extern volatile unsigned char XGIF_0; // DVUCP(0x0388)
extern volatile unsigned char XGIF_1; // DVUCP(0x0389)
extern volatile unsigned char XGIF_2; // DVUCP(0x038A)
extern volatile unsigned char XGIF_3; // DVUCP(0x038B)
extern volatile unsigned char XGIF_4; // DVUCP(0x038C)
extern volatile unsigned char XGIF_5; // DVUCP(0x038D)
extern volatile unsigned char XGIF_6; // DVUCP(0x038E)
extern volatile unsigned char XGIF_7; // DVUCP(0x038F)
extern volatile unsigned char XGIF_8; // DVUCP(0x0390)
extern volatile unsigned char XGIF_9; // DVUCP(0x0391)
extern volatile unsigned char XGIF_A; // DVUCP(0x0392)
extern volatile unsigned char XGIF_B; // DVUCP(0x0393)
extern volatile unsigned char XGIF_C; // DVUCP(0x0394)
extern volatile unsigned char XGIF_D; // DVUCP(0x0395)
extern volatile unsigned char XGIF_E; // DVUCP(0x0396)
extern volatile unsigned char XGIF_F; // DVUCP(0x0397)
extern volatile unsigned short XGMCTL; // DVUSP(0x0380)
extern volatile unsigned char XGMCTLHI; // DVUCP(0x0380)
extern volatile unsigned char XGMCTLLO; // DVUCP(0x0381)
extern volatile unsigned short XGPC; // DVUSP(0x039E)
extern volatile unsigned short XGR1; // DVUSP(0x03A2)
extern volatile unsigned short XGR2; // DVUSP(0x03A4)
extern volatile unsigned short XGR3; // DVUSP(0x03A6)
extern volatile unsigned short XGR4; // DVUSP(0x03A8)
extern volatile unsigned short XGR5; // DVUSP(0x03AA)
extern volatile unsigned short XGR6; // DVUSP(0x03AC)
extern volatile unsigned short XGR7; // DVUSP(0x03AE)
extern volatile unsigned short XGSEM; // DVUSP(0x039A)
extern volatile unsigned short XGSWT; // DVUSP(0x0398)
extern volatile unsigned short XGVBR; // DVUSP(0x0386)
extern volatile unsigned char _PORTAB[2];

extern volatile unsigned char _PORTAB[2];
extern volatile unsigned short * _PAB;

#define PORTS_BA (*((volatile unsigned short*)_PAB)) // wr

#define PORTA (_PORTAB[0]) // DVUCP(0x0000) wr
#define PORTB (_PORTAB[1]) // DVUCP(0x0001) wr
#define TCTL1_ADDR (&TCTL1) // r
#define TCTL2_ADDR (&TCTL2) // r
#define TC2_ADDR (&TC2) // r
#define TC3_ADDR (&TC3) // r
#define TC4_ADDR (&TC4) // r
#define TC5_ADDR (&TC5) // r
#define TC6_ADDR (&TC6) // r
#define TC7_ADDR (&TC7) // r
#define ATD0_BASE ((uintptr_t)&ATD0DR0)
#define ATD1_BASE ((uintptr_t)&ATD1DR0)
#define SCI0_BASE ((uintptr_t)&SCI0BD)

#define DVUCP(address) (*((volatile unsigned char*)(address)))
#define DVUSP(address) (*((volatile uintptr_t*)(address)))

#define AVUCP(address) ((volatile unsigned char*)(address))
#define AVUSP(address) ((volatile unsigned short*)(address))

//TODO: document why this has to be so stupid!
extern void _start()__attribute__((weak));
extern inline void receiveAndIncrement(const unsigned char value);
extern inline void sendAndIncrement(unsigned char rawValue);
extern void StackBurner();
extern void xgateThread0End(void);
extern void xgateThread0(void);


#endif

